name: Marketplace Deploys
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Install tfx-cli
        run: npm install -g tfx-cli
      - name: Publish extension
        run: tfx extension publish --manifest-globs vss-extension.json --token ${{ secrets.AZURE_DEVOPS_PAT }}
